CREATE DATABASE qlsv;
USE qlsv;
CREATE TABLE class(
ClassID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ClassName VARCHAR(60) NOT NULL,
StartDate DATETIME  NOT NULL,
Status  BIT 
);
CREATE TABLE student(
StudentID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
StudentName VARCHAR(30) NOT NULL,
Address VARCHAR(50),
Phone VARCHAR(10),
Status BIT,
ClassID INT NOT NULL,
FOREIGN KEY (ClassId) REFERENCES class(ClassID)
);

CREATE TABLE  ubject(
SubID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SubName VARCHAR(30) NOT NULL,
Credit Tinyint NOT NULL DEFAULT 1 CHECK (Credit>=1),
Status BIT DEFAULT 1
);

CREATE TABLE mark(
MarkID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SubID INT NOT NULL UNIQUE KEY,
StudentID INT NOT NULL UNIQUE KEY,
Mark  FLOAT DEFAULT 0 CHECK(Mark>=0 AND Mark<=100),
ExamTimes  TINYINT DEFAULT 1,
FOREIGN KEY(SubID)  REFERENCES Subject(SubID),
FOREIGN KEY(StudentID) REFERENCES Student(SdeudentID)

); 